### ISSUE TITLE
Null-pointer exception when determining cluster type

### ISSUE THREAD

**Issue by tun0** [GoogleCloudPlatform/autopilot-cost-calculator#2]
With my original `.kube/config`, I ran into the following error:
```
❯ ./autopilot-cost-calculator
panic: runtime error: index out of range [3] with length 1

goroutine 1 [running]:
main.main()
        /home/ruben/projects/GCP/autopilot-cost-calculator/main.go:71 +0xfa5
```
This was because I had customized the names of my contexts (more friendly names).

After switching it back to the original names, I got the following error:
```
❯ ./autopilot-cost-calculator
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15f6324]

goroutine 1 [running]:
main.main()
        /home/ruben/projects/GCP/autopilot-cost-calculator/main.go:81 +0x5c4
```
This seems to crash on determining whether the cluster is AutoPilot or Standard.

The cluster in question is a Standard cluster.
```
currentMasterVersion: 1.24.14-gke.2700
currentNodeVersion: 1.24.14-gke.1200
```

**Comment by sanusatyadarshi** [comment]
Getting the same error 

```
./autopilot-cost-calculator
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101abfbec]

goroutine 1 [running]:
main.main()
	/github/workspace/main.go:81 +0x48c
```

**Comment by kennycoder** [comment]
apologies for the late reply. will look into this asap.
